version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Argentina/Cordoba
    volumes:
      - type: volume
        source: myappdata
        target: /app/data

volumes:
  myappdata:
    driver: local
  esdata:
    driver: local
